### ISSUE TITLE
Need more jokes

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/LateNight#4]
I am building a dataset of jokes ("dad" jokes), family friendly, the more groan inducing the better! Please help me with links to places I can find more. Starting with 650 from https://icanhazdadjoke.com/

**Comment by Lachie-Source** [comment]
Why did the leprechaun cross the rainbow? To Get to the pot of gold!

**Comment by Lachie-Source** [comment]
> Why did the leprechaun cross the rainbow? To Get to the pot of gold!
i hate that joke actually don't use that lol

**Comment by fruitfont** [comment]
How do you fix a broken tomato? With tomato paste!

**Comment by Lemmings42** [comment]
Why does Norway have barcodes on their ships? Because they Scan-da-navy-in!

**Comment by Catz1301** [comment]
What's red and smells like blue paint? Red paint!

**Comment by AshikPaul42** [comment]
Check out [Jokes](https://github.com/15Dkatz/official_joke_api)

API : https://official-joke-api.appspot.com/jokes/ten

**Comment by AnonymousPyro** [comment]
Check it tooo !!
[Dataset](https://github.com/taivop/joke-dataset)

**Comment by AshikPaul42** [comment]
What do you call a bee that lives in America? A USB.

**Comment by Lemmings42** [comment]
https://rapidapi.com/KegenGuyll/api/dad-jokes/details

**Comment by w3cj** [comment]
https://www.kaggle.com/abhinavmoudgil95/short-jokes

**Comment by eminks** [comment]
> 
> 
> https://rapidapi.com/KegenGuyll/api/dad-jokes/details

Free api https://us-central1-dadsofunny.cloudfunctions.net/DadJokes/random/jokes

**Comment by violetcraze** [comment]
https://github.com/wesbos/dad-jokes (Raw file: https://raw.githubusercontent.com/wesbos/dad-jokes/master/readme.md)

**Comment by NeuroLife77** [comment]
https://github.com/pjimenezmateo/Computer-jokes/blob/master/jokes.txt

**Comment by violetcraze** [comment]
https://github.com/AlexLakatos/computer-puns/blob/master/puns.json

**Comment by NeuroLife77** [comment]
https://www.reddit.com/r/dadjokes/comments/76jfme/a_giant_list_of_puns/

**Comment by AshikPaul42** [comment]
Have you heard of the band 1023MB?.    They haven't got a gig yet.

**Comment by maixxq** [comment]
What do you get when you cross a snowman with a vampire?  Frostbite

**Comment by The-Decoder97** [comment]
https://textfiles.vistech.net/humor/

**Comment by NeuroLife77** [comment]
https://github.com/elijahmanor/devpun/blob/master/jokes.json

**Comment by AshikPaul42** [comment]
What do you call a bee that lives in America? A USB.

**Comment by yasquerda** [comment]
Bob the builder sat on a log, bob the builder got off the log to go home because he was tired

**Comment by w3cj** [comment]
Code to get the jokes from here: https://rapidapi.com/KegenGuyll/api/dad-jokes/endpoints

https://gist.github.com/w3cj/e988f0186702d7ddf4121023f22b3f34

My 50 jokes generated here: https://gist.github.com/w3cj/9332c248475472da15f583b4f6bd60f9

**Comment by YaBoiWaaaaafle** [comment]
​Would you rather have $400 or a matter baby?
Nothing. What's a matter with you?

**Comment by renx99** [comment]
I had a dream last night that I was a muffler. I woke up exhausted.

**Comment by NeuroLife77** [comment]
https://github.com/xasos/Puns/blob/master/Backend/puns.json

**Comment by AshikPaul42** [comment]
What did the duck say when he bought lipstick? Put it on my bill.

**Comment by maixxq** [comment]
What do you call cheese that isn't yours? Nacho Cheese.

**Comment by YaBoiWaaaaafle** [comment]
> ​Would you rather have $400 or a matter baby?
> Nothing. What's a matter with you?

You were supposed to say what is a matter baby.

**Comment by violetcraze** [comment]
How do you stop a dog barking in the back of the car? You put it in the front.

**Comment by AshikPaul42** [comment]
A DHCP packet walks into a bar and asks for a beer. The bartender says, here, but I’ll need that back in an hour!

**Comment by harshit99-cyber** [comment]
{
  setup: 'What do you call a nervous javelin thrower?',
  punchline: 'Shakespeare.',
  id: 223,
  type: 'general'
}
{
  punchline: 'It gets jalapeño face.',  
  id: 249,
  type: 'general',
  setup: 'What does an angry pepper do?'
}
{
  setup: "Did you hear about the chameleon who couldn't change color?",
  punchline: 'They had a reptile dysfunction.',
  id: 87,
  type: 'general'
}
{
  setup: 'How do you make holy water?',
  punchline: 'You boil the hell out of it.',
  id: 130,
  type: 'general'
}
{
  setup: 'Where do young cows eat lunch?',
  punchline: 'In the calf-ateria.',       
  id: 303,
  type: 'general'
}
{
  id: 326,
  type: 'general',
  setup: 'Why did Dracula lie in the wrong coffin?',
  punchline: 'He made a grave mistake.'
}
{
  setup: 'What do you call a bee that lives in America?',
  punchline: 'A USB.',
  id: 203,
  type: 'general'
}
{
  setup: 'How do you make holy water?',
  punchline: 'You boil the hell out of it',
  id: 53,
  type: 'general'
}
{
  id: 273,
  type: 'general',
  setup: 'What musical instrument is found in the bathroom?',
  punchline: 'A tuba toothpaste.'
}
{
  setup: 'What are the strongest days of the week?',
  punchline: 'Saturday and Sunday...the rest are weekdays.',
  id: 157,
  type: 'general'
}
{
  setup: "What is a tornado's favorite game to play?",
  punchline: 'Twister!',
  id: 254,
  type: 'general'
}
{
  setup: 'Why did the invisible man turn down the job offer?',
  punchline: "He couldn't see himself doing it",
  id: 52,
  type: 'general'
}
{
  setup: "What's the difference between a seal and a sea lion?",
  punchline: 'An ion! ',
  id: 286,
  type: 'general'
}
{
  setup: 'How many programmers does it take to change a lightbulb?',
  punchline: "None that's a hardware problem",
  id: 25,
  type: 'programming'
}
{
  setup: 'Why did the butcher work extra hours at the shop?',
  punchline: 'To make ends meat.',
  id: 63,
  type: 'general'
}
{
  setup: 'Why did the house go to the doctor?',
  punchline: 'It was having window panes.',
  id: 341,
  type: 'general'
}
{
  setup: 'What do you call a pile of cats?',
  punchline: ' A Meowtain.',
  id: 226,
  type: 'general'
}
{
  id: 375,
  type: 'general',
  setup: 'Why does Superman get invited to dinners?',
  punchline: 'Because he is a Supperhero.'
}
{
  setup: 'What happens when you anger a brain surgeon?',
  punchline: 'They will give you a piece of your mind.',
  id: 251,
  type: 'general'
}
{
  setup: 'What did the fish say when it swam into a wall?',
  punchline: 'Damn!',
  id: 184,
  type: 'general'
}
{
  setup: "Why can't your nose be 12 inches long?",
  punchline: "Because then it'd be a foot!",
  id: 322,
  type: 'general'
}

**Comment by w3cj** [comment]
Updated gist to write to the correct format: https://gist.github.com/w3cj/e988f0186702d7ddf4121023f22b3f34

My 50 generated jokes: https://gist.github.com/w3cj/419debb5895ce1094a1d29ad9f7df641

**Comment by renx99** [comment]
A pun has not completely matured until it's full groan.

**Comment by The-Decoder97** [comment]
https://textfiles.vistech.net/humor/

**Comment by renx99** [comment]
Two men walk into a bar, the third one ducks.

**Comment by yasquerda** [comment]
what did the dog say to the tree? nothing, he could only bark

**Comment by thanhvuxx122** [comment]
If Google can't find the answer, it's not a question.

**Comment by YaBoiWaaaaafle** [comment]
Here is how the joke goes: 
person 1: would you rather have 400 dollars or a matter baby?
Person 2: what's a matter baby?
person 1: nothing what's a matter with you?

**Comment by AshikPaul42** [comment]
What happens to a frog's car when it breaks down? It gets toad away

**Comment by Melvin-Abraham** [comment]
66 More Jokes
---
How many programmers does it take to change a light bulb? None. It's a hardware problem!
What does a proud computer call its little son? A microchip off the old block!
What is another name for a computer virus? A terminal illness!
Why did the computer spy quit? They couldn’t hack it anymore!
What did the motherboard say to the new software? I'll show you who's Dos!
What does a floppy disk do when it needs a break? It goes for a C: drive!
Why was the computer geek disappointed by the zoo? They couldn't find any RAM!
Which way did the computer programmer go? They went data way!
What do you get when you cross a computer with a hamburger? A Big Mac!
How do you find a spider on the internet? Check out its web site!
How did the computer catch a cold? Someone opened too many Windows!
Why don't Vikings like to send emails? They prefer to use Norse code!
What do you say when a JavaScript interview went bad? Don't call us, we'll callback you. We promise!
Why did the computer programmer drown? They couldn't figure out whether to float left or right!
How do you comfort a JavaScript bug? You console it!
Why did the programmer quit their job? Because they didn't get arrays!
What do computers and air conditioners have in common? They both become useless when you open Windows!
Why do Java programmers wear glasses? They cannot C#!
Do you know the band 1023 megabytes? They haven't had a gig yet!
Why was the database admin kicked out of the bar? They kept joining the tables.
Why did the JavaScript developer lose their job? They couldn't keep their Promises!
Did you hear about the monkeys who shared an Amazon account? They were Prime mates!
What are computers' favorite snacks? Microchips, phish sticks, and cookies. But just a few bytes of each!
Why was the network administrator late to work? There was lots of traffic congestion and even a collision. Everything was backed up. It was a hard drive!
What wedding gift should you buy for a Windows administrator? I don't know. Perhaps you should check the registry for clues!
Where's the best place to hide a body? Page two of Google!
What is the biggest lie in the entire universe? 'I have read and agree to the Terms & Conditions.'
What do computers do on a beach vacation? Surf the net!
Why are people afraid of computers? They byte!
Why do people on Twitter tell me I'm always confused? Because I don't follow!
How does a computer get drunk? It takes screenshots!
Why do app developer's have such high insurance rates? They're always crashing!
Why doesn't the developer use Git? Because they're afraid to commit!
Why does a front end developer eat alone? Because they don't know how to join the tables!
Did you hear about the Linux sysadmin who won Strictly? They really came out of their shell!
Why are Java programmers front yards so untidy? Because they are always waiting on garbage collection!
What do you call a Rails developer? A conductor!
Where do naughty disk drives get sent? Boot camp!
What do you call it when you have your mom's mom on speed dial? Instagram!
Why did the functions stop calling each other? Because they had constant arguments!
What's the most cutting edge language? C#!
Why couldn't the programmer dance to the song? Because they didn't get the algo-rhythm!
Why do universities hate Java programmers? They're always starting public classes!
Why are programmers popular on the street? They'll write scripts for anything at the right price!
Why is everyone who works at the keyboard factory so rich? They put in a lot of shifts!
Why don't programmers like nature? Too many bugs!
How many bits of bait does a programmer need to go fishing? At least 8, or else the fish won't byte!
Why were the Javascript plumbers delayed? Because they had to await async!
Why was the IT engineer in the hospital? They touched the firewall!
How do you generate a random string? Put a Windows user in front of vim and tell them to exit!
How many testers does it take to change a light bulb? None. Testers do not fix problems; they just report them!
How many programmers does it take to change a light bulb? What's the problem? The bulb at my desk works just fine!
Why did the programmer stop using Python? Because they are scared of snakes!
Why did the PowerPoint Presentation cross the road? To get to the other slide!
What sits on your shoulder and says 'Pieces of 7! Pieces of 7!'? A Parroty Error!
Why are database admins afraid of having dinner? Because the table is cleared!
Who is a computer's favorite singer? A Dell!
Why did the integer never get any radio play? Because it was unsigned!
How does the JavaScript function travel? It fly's first-class!
What is a computer's favorite instrument? The keyboard!
What does the hacker say to their mom when they're hacking people? Gone Phishing!
What do Linux users wear? Tux-edos!
What do you call a program whose file you can't find? Soft-where!
What grade did the programmer get on their test? C++!
What made the technician win the golf tournament? They had a hard-drive!
Why do programmers take so long in the shower? The instructions on the shampoo are: lather, rinse, repeat!

**Comment by AshikPaul42** [comment]
Where do young cows eat lunch? In the calf-ateria.

**Comment by renx99** [comment]
If you walk into a forest and cut down a tree, but the tree doesn't understand why you cut it down, do you think it's stumped?

**Comment by AshikPaul42** [comment]
Why do Java programmers wear glasses? Because they don't C#

**Comment by SwiftpotatoJT** [comment]
I like telling Dad jokes. Sometimes he laughs!

**Comment by GypsyDangerous** [comment]
Why do programmers always mix up Halloween and Christmas?, Because Oct 31 == Dec 25
 How do you make holy water?, You boil the hell out of it
 What do you call sad coffee?, Despresso.
 Did you hear about the guy whose whole left side was cut off?, He's all right now.
 Ever wondered why bees hum?, It's because they don't know the words.
 How do hens stay fit?, They always egg-cercise!
 How do you make holy water?, You boil the hell out of it.
 How does a French skeleton say hello?, Bone-jour.
 What do birds give out on Halloween?, Tweets.
 What do you call a duck that gets all A's?, A wise quacker.
 What do you call a group of disorganized cats?, A cat-tastrophe.
 What do you call an elephant that doesn’t matter?, An irrelephant.
 What do you call someone with no nose?, Nobody knows.
 What do you do when you see a space man?, Park your car man.
 What is a tornado's favorite game to play?, Twister!
 What kind of award did the dentist receive?, A little plaque.
 What kind of dinosaur loves to sleep?, A stega-snore-us.
 What's orange and sounds like a parrot?, A Carrot.
 What's the best thing about elevator jokes?, They work on so many levels.
 When does a joke become a dad joke?, When it becomes apparent.
 Who did the wizard marry?, His ghoul-friend
 Who is the coolest Doctor in the hospital?, The hip Doctor!
 Why are skeletons so calm?, Because nothing gets under their skin.
 Why do trees seem suspicious on sunny days?, Dunno they're just a bit shady.
 What is the least spoken language in the world?, Sign language

**Comment by YaBoiWaaaaafle** [comment]
Why did Adele cross the road? To say hello from the other side!

**Comment by arnavsirigere** [comment]
Just formatted someones jokes

How do you comfort a JavaScript bug? You console it
Why did the child component have such great self-esteem? Because its parent kept giving it `props`!
Why do C# and Java developers keep breaking their keyboards? Because they use a strongly typed language!"Why did the functional component feel lost? Because it didn't know what `state` it was in!
Why was the JavaScript developer sad? Because he didn't Node how to Express himself!
Why did the developer go broke? Because he used up all his cache!
Why did the React Higher Order Component give up? Because it sur-rendered to the prop-aganda!
When a JavaScript date has gone bad \"Don't call me I'll callback you. I promise!
Why did the react class component feel relieved? Because it was now off the hook
Why did the react developer have an addiction? Because they were completely hooked on the hooks proposal
What does a React proposal mean? It means to swallow something hook line and sinker
Why was the react developer late to everything? Because they were playing hooky with the hooks proposal
Why couldn’t the React component understand the joke? Because it didn’t get the context
Dev1 saw a strange JavaScript function & asked \"What is this?\". Dev2 responded \"I don't know. I would've called you but I was in a bind
Two JavaScript developers walked into the variable `bar`. Ouch!
Why did Jason cover himself with bubble wrap? Because he wanted to make a cross-domain JSONP request
Why did the software company hire drama majors from Starbucks? Because they needed JavaScript experts!
Why did the CoffeeScript developer keep getting lost? Because he couldn't find his source without a map!
What do you call __proto__? Dunder proto Michael Scott was the regional manager where? __mifflin__
How did the doctor revive the developer? The dev wasn't responsive so the doc picked him up by his bootstraps!
Why did the C# developer fall asleep? Because he didn't like Java
Why did the JavaScript boxer goto the chiropractor? Because his backbone was angular from a knockout and required attention!
How did the web dev hurt Comic Sans feelings? Once he saw the font he quickly changed to Open Sans and exclaimed \"In your @font-face!\
Why was Ember.js turning red? Because it was EMBERrassed for not remEMBERing its route home!
dev1 > What tool do you use to switch versions of node? dev1> nvm I figured it out
Why did the Web A11y Dev keep getting distracted? Beacuse they couldn't maintain focus!
How do you make a Web App accessible? ARIA kidding me?

**Comment by AshikPaul42** [comment]
What do you call a factory that sells passable products? A satisfactory!

**Comment by Lemmings42** [comment]
How do deaf triangles talk? Sine language!

**Comment by ravid7000** [comment]
https://gist.github.com/ravid7000/10210457c2d93247e0c8c7c41dcb4529

**Comment by harshit99-cyber** [comment]
How does a train eat? It goes chew, chew
What's the best time to go to the dentist? Tooth hurty.
What's the best thing about a Boolean? Even if you're wrong, you're only off by a bit.
What does C.S. Lewis keep at the back of his wardrobe? Narnia business!
Why did the mushroom get invited to the party? Because he was a fungi.
I'm reading a book about anti-gravity... It's impossible to put down
Want to hear a joke about a piece of paper? Never mind...it's tearable
If you boil a clown... Do you get a laughing stock?
Don't look at the eclipse through a colander. You'll strain your eyes.
Why do chicken coops only have two doors? Because if they had four, they would be chicken sedans
When a dad drives past a graveyard: Did you know that's a popular cemetery? Yep, people are just dying to get in there
I Got Hit In the Head By A Soda Can, But It Didn't Hurt That Much... It was a soft drink.
Did you hear the one about the guy with the broken hearing aid? Neither did he.
Have you heard the rumor going around about butter? Never mind, I shouldn't spread it.
How many bones are in the human hand? A handful of them.
How many kids with ADD does it take to change a lightbulb? Let's go ride bikes!
What biscuit does a short person like? Shortbread. 
What cheese can never be yours? Nacho cheese.
What creature is smarter than a talking parrot? A spelling bee.
What did one wall say to the other wall? I'll meet you at the corner!
What did the beaver say to the tree? It's been nice gnawing you.
What do birds give out on Halloween? Tweets.
What do you call a cow with no legs? Ground beef.
What do you call a fat psychic? A four-chin teller.
What do you call a pig that knows karate? A pork chop!
What do you call cheese by itself? Provolone.
What do you get when you cross a snowman with a vampire? Frostbite.
What is a vampire's favorite fruit? A blood orange.
What kind of award did the dentist receive? A little plaque.
What type of music do balloons hate? Pop music!
What's brown and sticky? A stick.
What's the worst thing about ancient history class? The teachers tend to Babylon.
What’s the difference between an African elephant and an Indian elephant? About 5000 miles.
Where do hamburgers go to dance? The meat-ball.
Why are skeletons so calm? Because nothing gets under their skin.
Why can't a bicycle stand on its own? It's two-tired.
Why can’t you hear a pterodactyl go to the bathroom? The p is silent.
Why did the burglar hang his mugshot on the wall? To prove that he was framed!
Why did the fireman wear red, white, and blue suspenders? To hold his pants up.
Why didn't the number 4 get into the nightclub? Because he is 2 square.
Did you know the first French fries weren't actually cooked in France? They were cooked in Greece
What is the least spoken language in the world? Sign language

**Comment by hkarrson** [comment]
Captain: You seem to be having trouble with the navigation... Navigator: Well, there's a big byte in the map! Sharkbait's pet parrot bit it! Captain: Arggg! I hate bitmaps!

**Comment by shiffman** [comment]
Thanks everyone! I'll return to this thread if I want to expand the joke database.

Noting another contribution also: https://github.com/CodingTrain/LateNight/pull/10
